export const GET_NEWEST_ARTICLES = "GET_NEWEST_ARTICLES";
export const GET_MOST_VIEWED_ARTICLES = "GET_MOST_VIEWED_ARTICLES";
export const GET_ONE_ARTICLE = "GET_ONE_ARTICLE";
export const GET_ARTICLES_BY_MOUNTAIN_NAME = "GET_ARTICLES_BY_MOUNTAIN_NAME";
export const RESET_ARTICLE = "RESET_ARTICLE";

//FOTOS
export const GET_RANDOM_PHOTO = "GET_RANDOM_PHOTO";
export const GET_ALL_PHOTOS_FOR_UI = "GET_ALL_PHOTOS_FOR_UI";
export const GET_MOUNTAINS_NAME_LIST_PHOTOS = "GET_MOUNTAINS_NAME_LIST_PHOTOS";
export const GET_ONE_PHOTO_FOR_UI = "GET_ONE_PHOTO_FOR_UI";
//SYSTEM
export const GET_ALL_SYSTEMS = "GET_ALL_SYSTEMS";
