export const ACTIVE_LINK = "ACTIVE_LINK";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
//ARTICLE
export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES";
export const REQUEST_ARTICLE = "REQUEST_ARTICLE";
export const DELETE_ONE_ARTICLE = "DELETE_ONE_ARTICLE";
export const GET_ONE_ARTICLE = "GET_ONE_ARTICLE";
export const EDIT_ARTICLE = "EDIT_ARTICLE";
export const SAVE_ARTICLE = "SAVE_ARTICLE";
export const BACK_TO_ARTICLES_LIST = "BACK_TO_ARTICLES_LIST";
//MOUNTAINS
export const GET_ALL_MOUNTAINS = "GET_ALL_MOUNTAINS";
export const GET_ONE_MOUNTAIN = "GET_ONE_MOUNTAIN";
export const ADD_NEW_MOUNTAIN = "ADD_NEW_MOUNTAIN";
export const SAVE_MOUNTAIN = "SAVE_MOUNTAIN";
export const EDITED_MOUNTAIN = "EDITED_MOUNTAIN";
export const REQUEST_MOUNTAINS = "REQUEST_MOUNTAINS";
export const BACK_TO_MOUNTAINS_LIST = "BACK_TO_MOUNTAINS_LIST";
export const DELETE_ONE_MOUNTAIN = "DELETE_ONE_MOUNTAIN";
//COUNTRIES
export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES";
export const GET_ONE_COUNTRIES = "GET_ONE_COUNTRIES";
export const REQUEST_COUNTRIES = "REQUEST_COUNTRIES";
export const EDIT_COUNTRIES = "EDIT_COUNTRIES";
export const ADD_NEW_COUNTRIES = "ADD_NEW_COUNTRIES";
export const BACK_TO_COUNTRIES_LIST = "BACK_TO_COUNTRIES_LIST";
export const EDITED_COUNTRY = "EDITED_COUNTRY";
export const DELETE_ONE_COUNTRY = "DELETE_ONE_COUNTRY";
//SYSTEMS
export const GET_ALL_SYSTEMS = "GET_ALL_SYSTEMS";
export const REQUEST_SYSTEMS = "REQUEST_SYSTEMS";
export const ADD_NEW_SYSTEM = "ADD_NEW_SYSTEM";
export const GET_ONE_SYSTEM = "GET_ONE_SYSTEM";
export const SAVE_SYSTEM = "SAVE_SYSTEM";
export const EDITED_SYSTEM = "EDITED_SYSTEM";
export const DELETE_ONE_SYSTEM = "DELETE_ONE_SYSTEM";
